#ifndef HOOK_TPPMARKERTYPE_H
#define HOOK_TPPMARKERTYPE_H

enum TppMarkerType {
    MARKER_TYPE_FOB_ENEMY = 0x200005,
    MARKER_TYPE_BUDDY_D_DOG = 0x1c,
    MARKER_TYPE_BUDDY_QUIET = 0x1d,
};

#endif // HOOK_TPPMARKERTYPE_H
